---
name: Load Parameters
description: Load parameters for the build job

outputs:
  build_matrix:
    description: Build matrix
    value: ${{ steps.set-matrix.outputs.build_matrix }}

  docker_image:
    description: Docker image
    value: ${{ steps.get-docker-image.outputs.image_name }}

runs:
  using: "composite"
  steps:
    - name: Set Build Matrix
      id: set-matrix
      uses: actions/github-script@v7
      with:
        script: |
          const file = require('./ci/MACHINES.json');
          const matrix = Object.entries(file).map(([machine, kas_file]) => ({ machine, kas_file }));
          core.setOutput('build_matrix', JSON.stringify(matrix));
          console.log(matrix);

    - name: Get Docker Image
      id: get-docker-image
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs')
          const image = fs.readFileSync('./ci/DOCKER_IMAGE.txt').toString().trim()
          core.setOutput('image_name', image)
          console.log(image)
