---
name: Load parameters
description: Load parameters for the build job

outputs:
  build_matrix:
    description: Build matrix
    value: ${{ steps.set-matrix.outputs.build_matrix }}

  docker_image:
    description: Docker image
    value: ${{ steps.get-docker-image.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: Set build matrix
      id: set-matrix
      uses: actions/github-script@v7
      with:
        script: |
          const file = require('./ci/MACHINES.json');
          const matrix = Object.entries(file).map(([machine, kas_file]) => ({ machine, kas_file }));
          core.setOutput('build_matrix', JSON.stringify(matrix));
          console.log(matrix);

    - name: Get docker image
      id: get-docker-image
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs')
          const image = fs.readFileSync('./ci/DOCKER_IMAGE.txt').trim()
          console.log(image)
          return image
