name: Pull Image
description: Pull Docker Image Action

inputs:
  image_name:
    description: The name of the Docker image to pull
    required: true

  github_token:
    description: GitHub token for authentication
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to ghcr
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Pull Docker Image
      shell: bash
      run: |
        echo "Pulling Docker image: ${{ inputs.image_name }}"
        docker pull ghcr.io/audioreach/${{ inputs.image_name }}
        docker tag ghcr.io/audioreach/${{ inputs.image_name }} ${{ inputs.image_name }}
        echo "Docker image pulled successfully"
