---
name: post_merge_build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  load_parameters:
    uses: ./.github/workflows/REUSABLE_WORKFLOW_loading.yml

  build:
    needs: load_parameters
    uses: ./.github/workflows/REUSABLE_WORKFLOW_build.yml
    with:
      build_matrix: ${{ needs.load_parameters.outputs.build_matrix }}
      docker_image: ${{ needs.load_parameters.outputs.docker_image }}
