---
name: pre_merge
run-name: pre_merge ${{ github.event.pull_request.number != '' && github.event.pull_request.number || '' }}
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - mains
    paths-ignore:
      - .github/*

jobs:
  build:
    uses: Audioreach/meta-ar/.github/workflows/REUSABLE_WORKFLOW_build.yml@main