---
name: pre_merge_build
run-name: Pre Merge Build ${{ github.event.pull_request.number != '' && github.event.pull_request.number || '' }}
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  load_parameters:
    uses: ./.github/workflows/REUSABLE_WORKFLOW_loading.yml

  build:
    needs: load_parameters
    uses: ./.github/workflows/REUSABLE_WORKFLOW_build.yml
    with:
      build_matrix: ${{ needs.load_parameters.outputs.build_matrix }}
      docker_image: ${{ needs.load_parameters.outputs.docker_image }}
      