name: Qualcomm Preflight Checks

on:
  pull_request_target:
    branches: [ Yocto_new_test ]
  push:
    branches: [ Yocto_new_test ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  qcom-preflight-checks:
    uses: Audioreach/audioreach-workflows/.github/workflows/qcom-preflight-checks.yml@master
    secrets: inherit

  yocto-layer-check:
    name: Yocto Layer Sanity Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Layer Repo
        uses: actions/checkout@v3

      - name: Install Yocto Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gawk wget git-core diffstat unzip texinfo gcc build-essential \
            chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping \
            python3-git python3-jinja2 libegl-mesa0 libsdl1.2-dev pylint

      - name: Clone Poky and Meta-OpenEmbedded
        run: |
          git clone https://git.yoctoproject.org/poky -b master
          git clone https://git.openembedded.org/meta-openembedded
      - name: Source Environment and Run Layer Check
        run: |
          cd poky
          source oe-init-build-env build
          bitbake-layers add-layer ../../meta-openembedded/meta-oe
          bitbake-layers add-layer ../../meta-openembedded/meta-python
          bitbake-layers add-layer ../../meta-openembedded/meta-multimedia
          bitbake-layers add-layer ../../meta-openembedded/meta-networking
          bitbake-layers add-layer ../../../meta-ar
          #rm -rf ../bitbake/lib/layerindexlib/tests/testdata  # <-- This line fixes the issue
          bitbake-layers show-layers
          yocto-check-layer ../../../../meta-ar
