---
name: _build
on:
  workflow_call:
    inputs:
      build_matrix:
        required: true
        type: string
        description: Build matrix for the build job

      docker_image:
        required: true
        type: string
        description: Docker image to use for the build job

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        build_matrix: ${{ fromJson(inputs.build_matrix) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Clone meta-qcom repository
        run: |
          # Clone the meta-qcom repository
          cd ${{ github.workspace }}/..
          # Check if the directory already exists
          if [ -d "meta-qcom" ]; then
            echo "Directory meta-qcom already exists. Pulling latest changes."
            cd meta-qcom
            git reset --hard origin/master
            git pull origin master
          else
            echo "Directory meta-qcom does not exist. Cloning repository."
            git clone https://github.com/qualcomm-linux/meta-qcom.git
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get UID and GID
        id: ids
        run: |
          echo "uid=$(id -u)" >> $GITHUB_OUTPUT
          echo "gid=$(id -g)" >> $GITHUB_OUTPUT

      - name: Build for ${{ matrix.build_matrix.machine }}
        uses: ./.github/actions/build
        with:
          docker_image: ${{ inputs.docker_image }}
          uid: ${{ steps.ids.outputs.uid }}
          gid: ${{ steps.ids.outputs.gid }}
          kas_file: ${{ matrix.build_matrix.kas_file }}
        env:
          MACHINE: ${{ matrix.build_matrix.machine }}

      - name: Cleanup Workspace
        run: |
          # Cleanup the workspace
          rm -rf ${{ github.workspace }}/..
          echo "Workspace cleaned up."
