---
name: _loading
description: Load required parameters for the subsequent jobs

on:
  workflow_call:
    outputs:
      build_matrix:
        description: Build matrix
        value: ${{ jobs.loading.outputs.build_matrix }}

      docker_image:
        description: Docker image
        value: ${{ jobs.loading.outputs.docker_image }}

jobs:
  loading:
    runs-on: ubuntu-latest
    outputs:
      build_matrix: ${{ steps.loading.outputs.build_matrix }}
      docker_image: ${{ steps.loading.outputs.docker_image }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Load Parameters
        id: loading
        uses: ./.github/actions/loading
