---
name: _build
on:
  workflow_call:
    inputs:
      build_matrix:
        required: true
        type: string
        description: Build matrix for the build job

      docker_image:
        required: true
        type: string
        description: Docker image to use for the build job

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        build_matrix: ${{ fromJson(inputs.build_matrix) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Clone meta-qcom repository
        run: |
          # Clone the meta-qcom repository
          cd ${{ github.workspace }}/..
          # Check if the directory already exists
          if [ -d "meta-qcom" ]; then
            echo "Directory meta-qcom already exists. Pulling latest changes."
            cd meta-qcom
            git reset --hard origin/master
            git pull origin master
          else
            echo "Directory meta-qcom does not exist. Cloning repository."
            git clone https://github.com/qualcomm-linux/meta-qcom.git
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get UID and GID
        id: ids
        run: |
          echo "uid=$(id -u)" >> $GITHUB_OUTPUT
          echo "gid=$(id -g)" >> $GITHUB_OUTPUT

      - name: Build for ${{ matrix.build_matrix.machine }}
        run: |
          #!/bin/bash
          set -e

          # Define variables
          USER_ID=${{ steps.ids.outputs.uid }}
          GROUP_ID=${{ steps.ids.outputs.gid }}
          WORKSPACE=${{ github.workspace }}/..
          SSH_DIR="/usr2/$USER/.ssh"
          GITCONFIG="/usr2/$USER/.gitconfig"
          USER_HOME="/home/$USER"

          docker run \
            -u ${USER_ID}:${GROUP_ID} \
            --rm \
            -v ${WORKSPACE}:${USER_HOME}/workspace \
            -v ${SSH_DIR}:${USER_HOME}/.ssh \
            -v ${GITCONFIG}:${USER_HOME}/.gitconfig \
            -w ${USER_HOME}/workspace \
            --privileged \
            ${{ inputs.docker_image }} \
            bash -c "
              set -e
              kas shell meta-ar/ci/${{ matrix.build_matrix.kas_file }} -c '
                cd ../meta-qcom
                git fetch git@github.com:qualcomm-linux/meta-qcom.git 78f13cf900b6df8176cbe722576aebbdf9a4d70d && git cherry-pick FETCH_HEAD
                cd ../build
                umask 022
                bitbake packagegroup-qcom-audio
              '
            "
